export const players = [
  {
    name: 'Stephen Curry',
    number: '30',
    position: 'guard',
    pseudo: 'curry',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Donte DiVincenzo',
    number: '0',
    position: 'guard',
    pseudo: 'divizenco',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Draymond Green',
    number: '23',
    position: 'forward',
    pseudo: 'green',
    img: `../i/players/${this.pseudo}.webp`,
  },
  {
    name: 'JaMychal Green',
    number: '1',
    position: 'forward-center',
    pseudo: 'green-gm',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Andre Iguodala',
    number: '9',
    position: 'guard-forward',
    pseudo: 'iguodala',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Kevon Looney',
    number: '5',
    position: 'forward',
    pseudo: 'looney',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Klay Thompson',
    number: '11',
    position: 'guard',
    pseudo: 'thompson',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Andrew Wiggins',
    number: '22',
    position: 'forward',
    pseudo: 'wiggin',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Gary Payton II',
    number: '8',
    position: 'guard',
    pseudo: 'payton',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'James Wiseman',
    number: '33',
    position: 'center',
    pseudo: 'wiseman',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Ty Jerome',
    number: '10',
    position: 'guard-forward',
    pseudo: 'jerome',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Jordan Poole',
    number: '3',
    position: 'guard',
    pseudo: 'poole',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Anthony Lamb',
    number: '40',
    position: 'forward',
    pseudo: 'lamb',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Jonathan Kuminga',
    number: '00',
    position: 'forward',
    pseudo: 'kuminga',
    img: `../i/players/${this.pseudo}`,
  },
  {
    name: 'Moses Moody',
    number: '4',
    position: 'guard',
    pseudo: 'moody',
    img: `../i/players/${this.pseudo}`,
  },
];

export const playersId =
  '?player_ids[]=224&player_ids[]=475&player_ids[]=7155648&player_ids[]=131&player_ids[]=185&player_ids[]=2189&player_ids[]=187&player_ids[]=354720&player_ids[]=17553979&player_ids[]=666848&player_ids[]=282&player_ids[]=443&player_ids[]=17553992&player_ids[]=115&player_ids[]=666676';
